version: "3.8"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama-cpu
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORCHESTRATOR=cpu
    restart: unless-stopped

volumes:
  ollama_data:
